version: "3.5"

services:
  backend_project_db:
    container_name: backend_project_db
    image: mysql:8
    restart: always
    build: manifests/setdb
    ports:
      - 3310:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: demo



